### ISSUE TITLE
license

### ISSUE THREAD

**Issue by colek42** [notedit/janus-go#1]
Thanks for making this public!  Would you mind adding a license to it

**Comment by cameronelliott** [comment]
Please add a LICENSE file. 

You may not be aware of this, but legally, without a license, no one can use your code:
[https://opensource.stackexchange.com/a/1721/4977](https://opensource.stackexchange.com/a/1721/4977)

The very popular Pion package currently uses this package, but might be worried due to the lack of any License file:
[https://github.com/pion/example-webrtc-applications/blob/master/janus-gateway/streaming/main.go#L7](https://github.com/pion/example-webrtc-applications/blob/master/janus-gateway/streaming/main.go#L7)

MIT would be compatible with the popular Pion package.
[https://github.com/pion/webrtc/blob/master/LICENSE](https://github.com/pion/webrtc/blob/master/LICENSE)

I would also like to use your package, but am worried due to the lack of any License file.

**Comment by notedit** [comment]
Done

**Comment by cameronelliott** [comment]
Thank you very much.
